services:
  mp_postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev
    ports:
      - "127.0.0.1:5423:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
